from yacs.config import CfgNode as CN
CFG = CN()

CFG.EXPERIMENT = CN()
CFG.EXPERIMENT.PROJECT = None
CFG.EXPERIMENT.NAME = None
CFG.EXPERIMENT.TAG = None
CFG.EXPERIMENT.SEED_VALUE = 42
CFG.EXPERIMENT.ALGO_DETER = True

CFG.DATASET = CN()
CFG.DATASET.TRAIN_VAL_SETS = None
CFG.DATASET.TEST_SET = None
CFG.DATASET.SPLIT_SPECS = [{}]
CFG.DATASET.LOAD_SPECS = [{}]
CFG.DATASET.AUGMENT_SPECS = [{}]
CFG.DATASET.NUM_WORKERS = 0
CFG.DATASET.BATCH_SIZE = 0

CFG.MODELER = CN()
CFG.MODELER.TYPE = None
CFG.MODELER.PRE_PATH = None
CFG.MODELER.MODEL = None
CFG.MODELER.MODEL_PRE_PATH = None
CFG.MODELER.MODEL_SPECS = [{}]
CFG.MODELER.LOSS_TYPE = None
CFG.MODELER.LOSS_SPECS = [{}]

CFG.SOLVER = CN()
CFG.SOLVER.TRAINER = None
CFG.SOLVER.TESTER = None
CFG.SOLVER.BATCH_SIZE = 0
CFG.SOLVER.EPOCHS = 0
CFG.SOLVER.OPTIMIZER_TYPE = None
CFG.SOLVER.OPTIMIZER_SPECS = [{}]
CFG.SOLVER.LR = 0.0
CFG.SOLVER.SCHEDULER_TYPE = None
CFG.SOLVER.SCHEDULER_SPECS = [{}]
CFG.SOLVER.PATIENCE = 0
CFG.SOLVER.LOG_PREFIX = "../Output"
